#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

protected_branches='refs/heads/dev refs/heads/live'

while read local_ref local_sha remote_ref remote_sha
do
  if [[ $protected_branches =~ $remote_ref ]]; then
    echo "Push to $remote_ref branch disallowed"
    exit 1
  fi
done

exit 0
