name: Test Branch Checkout Behavior

on: 
  workflow_dispatch:

jobs:
  test-checkout-behavior:
    runs-on: ubuntu-latest
    
    steps:
      - name: Show workflow context
        run: |
          echo "🔍 Workflow Context:"
          echo "Selected branch from dropdown: ${{ github.ref_name }}"
          echo "Full ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "---"
      
      - name: Checkout WITHOUT explicit ref
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Show what branch was actually checked out
        run: |
          echo "📂 Actual checkout results:"
          echo "Current branch: $(git branch --show-current)"
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Current commit short: $(git rev-parse --short HEAD)"
          echo "---"
          
      - name: Show recent commits to confirm which branch
        run: |
          echo "📝 Recent commits on checked out branch:"
          git log --oneline -3
          echo "---"
          
      - name: List all branches to see what's available
        run: |
          echo "🌿 Available branches:"
          git branch -a
